--             [ INTEGRANTES DO GRUPO ]                  --
--  Carlos Henrique Hannas de Carvalho  NºUSP: 11965988  --
--  Guilherme Azevedo Escudeiro         NºUSP: 11345600  --
--  Leonardo Hannas de Carvalho Santos  NºUSP: 11800480  --
--  Lucas Carvalho Freiberger Stapf     NºUSP: 11800559  --
-----------------------------------------------------------


-- (JA ESTA FUNCIONANDO)
-- Retorna a linha da tabela AVALIACAO_VENDA de maior valor de VENDA
SELECT AV.COLECIONADOR_1, AV.DATA_HORA, AV.NEGOCIACAO, AV.COLECIONADOR_2 FROM AVALIACAO_VENDA AV
    JOIN VENDA V ON AV.NEGOCIACAO = V.NEGOCIACAO AND AV.COLECIONADOR_2 = V.COLECIONADOR
    WHERE V.VALOR = (SELECT MAX(VALOR) FROM VENDA);


-- (JA ESTAO FUNCIONANDO)
-- Retorna a linha da tabela AVALIACAO de maior valor de VENDA
SELECT A.COLECIONADOR, A.DATA_HORA, A.NOTA, A.COMENTARIO FROM AVALIACAO A
    JOIN AVALIACAO_VENDA AV ON A.COLECIONADOR = AV.COLECIONADOR_1 AND A.DATA_HORA = AV.DATA_HORA
    JOIN VENDA V ON AV.NEGOCIACAO = V.NEGOCIACAO AND AV.COLECIONADOR_2 = V.COLECIONADOR
        WHERE V.VALOR = (SELECT MAX(VALOR) FROM VENDA);

SELECT NOTA, COMENTARIO
    FROM VENDA V JOIN AVALIACAO_VENDA AV
    ON V.NEGOCIACAO = AV.NEGOCIACAO AND V.VALOR = (SELECT MAX(VALOR) FROM VENDA)
    JOIN AVALIACAO A
    ON A.COLECIONADOR = AV.COLECIONADOR_1 AND A.DATA_HORA = AV.DATA_HORA;


-- Seleciona a média de completude do Álbum Virtual mais criado
SELECT ALBUM
    FROM ALBUM_VIRTUAL
    GROUP BY ALBUM, COLECIONADOR
    ORDER BY ALBUM DESC;

SELECT * FROM ALBUM_VIRTUAL;


































-- Retornar o Álbum Virtual mais criado e a sua média de completude
SELECT * FROM ALBUM_VIRTUAL
    GROUP BY COLECIONADOR, ALBUM
    ORDER BY ALBUM DESC;



