--             [ INTEGRANTES DO GRUPO ]                  --
--  Carlos Henrique Hannas de Carvalho  NºUSP: 11965988  --
--  Guilherme Azevedo Escudeiro         NºUSP: 11345600  --
--  Leonardo Hannas de Carvalho Santos  NºUSP: 11800480  --
--  Lucas Carvalho Freiberger Stapf     NºUSP: 11800559  --
-----------------------------------------------------------

-- Retorna a linha da tabela AVALIACAO_VENDA de maior valor de VENDA --
SELECT *
    FROM AVALIACAO_VENDA AV JOIN VENDA V
        ON AV.NEGOCIACAO = V.NEGOCIACAO AND AV.COLECIONADOR_2 = V.COLECIONADOR
        WHERE V.VALOR = (SELECT MAX(VALOR) FROM VENDA);

-- Retorna a tabela AVALIACAO de maior valor de VENDA --
SELECT A.COLECIONADOR, A.DATA_HORA, A.NOTA, A.COMENTARIO
    FROM AVALIACAO A JOIN AVALIACAO_VENDA AV
        ON A.COLECIONADOR = AV.COLECIONADOR_1 AND A.DATA_HORA = AV.DATA_HORA
        JOIN VENDA V
            ON AV.NEGOCIACAO = V.NEGOCIACAO AND AV.COLECIONADOR_2 = V.COLECIONADOR
            WHERE V.VALOR = (SELECT MAX(VALOR) FROM VENDA);

    SELECT NOTA, COMENTARIO
        FROM VENDA V JOIN AVALIACAO_VENDA AV
            ON V.NEGOCIACAO = AV.NEGOCIACAO AND V.VALOR = (SELECT MAX(VALOR) FROM VENDA)
            JOIN AVALIACAO A
                ON A.COLECIONADOR = AV.COLECIONADOR_1 AND A.DATA_HORA = AV.DATA_HORA;


-- Seleciona a média de completude do ÁLBUM VIRTUAL mais criado --
SELECT AL.ISBN, AL.TITULO, TOTAL_FIG / MAX_FIG AS "Completude do Album"
    FROM (SELECT AVF.ALBUM_V, COUNT(*) AS "TOTAL_FIG"
        FROM ALBUM_VIRTUAL_FIGURINHA AVF
        GROUP BY AVF.ALBUM_V) TABELA_MF
        JOIN (SELECT A.ISBN, SUM(A.NROFIGURINHAS) AS "MAX_FIG"
            FROM ALBUM A JOIN ALBUM_VIRTUAL AV
                ON A.ISBN = AV.ALBUM
            GROUP BY A.ISBN) TABELA_TF
            ON TABELA_MF.ALBUM_V = TABELA_TF.ISBN
            JOIN ALBUM AL
                ON AL.ISBN = TABELA_TF.ISBN;


-- Seleciona FIGURINHA de alguma Copa vendida pela BANCA localizada na 'Rua Thiago Silva, 3'
SELECT BF.ALBUM, BF.IDENTIFICADOR, COUNT(*)
    FROM BANCA_FIGURINHA BF JOIN BANCA B
        ON BF.BANCA = B.CNPJ
        JOIN ALBUM A ON BF.ALBUM = A.ISBN
        WHERE UPPER(B.ENDERECO) = 'RUA THIAGO SILVA, 3' AND UPPER(A.TITULO) LIKE '%CUP%'
        GROUP BY BF.ALBUM, BF.IDENTIFICADOR;


-- Seleciona AVALIACOES de NEGOCIACAO de VENDA ordenada por nota --
SELECT A.NOTA, A.COMENTARIO
    FROM AVALIACAO A JOIN AVALIACAO_VENDA AV
        ON A.COLECIONADOR = AV.COLECIONADOR_1 AND A.DATA_HORA = AV.DATA_HORA
    ORDER BY NOTA;

-- Seleciona COLECIONADORES que possuem ALBUM do 'Pica-Pau' e 'Copa' simultaneamente --