--               [ INTEGRANTES DO GRUPO ]                --
--  Carlos Henrique Hannas de Carvalho  NºUSP: 11965988  --
--  Guilherme Azevedo Escudeiro         NºUSP: 11345600  --
--  Leonardo Hannas de Carvalho Santos  NºUSP: 11800480  --
--  Lucas Carvalho Freiberger Stapf     NºUSP: 11800559  --
-----------------------------------------------------------


-- Tabela Cargo --
CREATE TABLE CARGO (
    CPF CHAR(14) NOT NULL,
    CARGO CHAR(4) NOT NULL,
    CONSTRAINT CK_CARGO CHECK (UPPER(CARGO) IN ('ADM', 'USER')),
    CONSTRAINT PK_CARGO PRIMARY KEY (CPF)
);

-- Tabela Administrador --
CREATE TABLE ADMINISTRADOR (
    CPF CHAR(14) NOT NULL,
    NOME VARCHAR2(30) NOT NULL,
    ENDERECO VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_ADM PRIMARY KEY (CPF),
    CONSTRAINT FK_ADM FOREIGN KEY (CPF) REFERENCES CARGO(CPF) ON DELETE CASCADE
);

-- Tabela Colecionador --
CREATE TABLE COLECIONADOR (
    CPF CHAR(14) NOT NULL,
    NOME VARCHAR2(30) NOT NULL,
    ENDERECO VARCHAR2(50) NOT NULL,
    REPUTACAO NUMBER(2,1),
    CONSTRAINT CK_REPUTACAO CHECK (REPUTACAO >= 0 AND REPUTACAO <= 5),
    CONSTRAINT PK_COLECIONADOR PRIMARY KEY (CPF),
    CONSTRAINT FK_COLECIONADOR FOREIGN KEY (CPF) REFERENCES CARGO(CPF) ON DELETE CASCADE
);

-- Tabela Banimento --
CREATE TABLE BANIMENTO (
    ADMINISTRADOR CHAR(14) NOT NULL,
    COLECIONADOR CHAR(14) NOT NULL,
    DATA_HORA DATE,
    DURACAO INT NOT NULL, -- Numero total de horas
    CONSTRAINT PK_BANIMENTO PRIMARY KEY (ADMINISTRADOR, COLECIONADOR, DATA_HORA),
    CONSTRAINT FK1_BANIMENTO FOREIGN KEY (ADMINISTRADOR) REFERENCES ADMINISTRADOR(CPF),  -- PERGUNTAR SE PRECISA DE ALGUM ON DELETE ...
    CONSTRAINT FK2_BANIMENTO FOREIGN KEY (COLECIONADOR) REFERENCES COLECIONADOR(CPF)
);

-- Tabela Avaliacao --
CREATE TABLE AVALIACAO (
    COLECIONADOR CHAR(14) NOT NULL,
    DATA_HORA DATE NOT NULL,
    NOTA NUMBER(2,1),
    COMENTARIO VARCHAR2(120),
    TIPO CHAR(5) NOT NULL,
    CONSTRAINT CK_TIPO CHECK (UPPER(TIPO) IN ('TROCA', 'VENDA')),
    CONSTRAINT PK_AVALIACAO PRIMARY KEY (COLECIONADOR, DATA_HORA),
    CONSTRAINT FK_AVALIACAO FOREIGN KEY (COLECIONADOR) REFERENCES COLECIONADOR(CPF) ON DELETE CASCADE
);
